@local_host = http://localhost:8080
@proxymock_host = http://localhost:4143
@ecs_host = http://newboots-ecs-alb-1410550651.us-east-1.elb.amazonaws.com

@host = {{proxymock_host}}
# @host = {{local_host}}

### Home endpoint
GET {{host}}/
Accept: application/json

### Health check endpoint
GET {{host}}/healthz
Accept: application/json

### Greeting endpoint with customizable name
GET {{host}}/greeting?name=TestUser
Accept: application/json

### NASA APOD data
GET {{host}}/nasa
Accept: application/json

### SpaceX latest launch data
GET {{host}}/spacex
Accept: application/json

### ZIP processing (default)
GET {{host}}/zip
Accept: application/json

### ZIP processing with specific file
GET {{host}}/zip?filename=jquery
Accept: application/json

### Location POST (echoes back location data)
POST {{host}}/location
Content-Type: application/json
Accept: application/json

{
  "locationID": "loc-001",
  "latitude": 37.7749,
  "longitude": -122.4194,
  "macAddress": "00:1A:2B:3C:4D:5E",
  "ipv4": "192.168.1.1"
}

### Number to words conversion
GET {{host}}/number-to-words?number=123
Accept: application/json

### Inventory search by item
GET {{host}}/inventory/search?key=item&value=journal
Accept: application/json

### Inventory search by qty
GET {{host}}/inventory/search?key=qty&value=25
Accept: application/json

### Inventory search by status
GET {{host}}/inventory/search?key=status&value=A
Accept: application/json

### Pet types (all breeds)
GET {{host}}/pets/types
Accept: application/json

### Pet types (search by dog breeds)
GET {{host}}/pets/types?type=dog
Accept: application/json

### Pet types (search by cat breeds)
GET {{host}}/pets/types?type=cat
Accept: application/json

### Inventory search by size.h (height)
GET {{host}}/inventory/search?key=size.h&value=14
Accept: application/json
