metadata:
  annotations:
    sidecar.speedscale.com/inject: "true"
    sidecar.speedscale.com/tls-out: "true"
    sidecar.speedscale.com/tls-java-tool-options: "true"

spec:
  template:
    metadata:
      annotations:
        sidecar.speedscale.com/inject: "true"
        sidecar.speedscale.com/tls-out: "true"
        sidecar.speedscale.com/tls-java-tool-options: "true" 