apiVersion: apps/v1
kind: Deployment
metadata:
  name: newboots-client
  labels:
    app: newboots-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newboots-client
  template:
    metadata:
      labels:
        app: newboots-client
    spec:
      containers:
        - name: newboots-client
          image: ghcr.io/kenahrens/newboots-client:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: BASE_URL
              value: "http://newboots-server:80"
            - name: APP_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: "0.1"
              memory: 256Mi
            limits:
              cpu: "0.5"
              memory: 512Mi 