apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "newboots"
            - name: MYSQL_USER
              value: "newboots"
            - name: MYSQL_PASSWORD
              value: "newboots"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          args:
            - --default-authentication-plugin=mysql_native_password
      volumes:
        - name: mysql-data
          emptyDir: {} 