apiVersion: v1
kind: Service
metadata:
  name: newboots-server
  labels:
    app: newboots-server
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: grpc
      port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    app: newboots-server 