name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:8
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn test

      - name: Run Checkstyle linter
        run: mvn checkstyle:check

      - name: Build JAR
        run: mvn clean package

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client Docker image
        run: |
          docker build -f Dockerfile.client -t ghcr.io/kenahrens/newboots-client:latest .
          docker push ghcr.io/kenahrens/newboots-client:latest

      - name: Build and push server Docker image
        run: |
          docker build -f Dockerfile.server -t ghcr.io/kenahrens/newboots-server:latest .
          docker push ghcr.io/kenahrens/newboots-server:latest

      - name: Check k8s manifest image
        run: make check-k8s-image 