name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:8
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn test

      - name: Build JAR
        run: mvn clean package

      - name: Read version from VERSION file
        id: version
        run: |
          VERSION=$(cat VERSION | tr -d '\n\r')
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            # For main branch, use VERSION file as-is
            BUILD_VERSION="${VERSION}"
          else
            # For PRs, append PR number to version from file
            BUILD_VERSION="${VERSION}-pr${{ github.event.number }}"
          fi
          echo "VERSION=${BUILD_VERSION}" >> $GITHUB_OUTPUT
          echo "Building version: ${BUILD_VERSION} (from VERSION file: ${VERSION})"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.client
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kenahrens/newboots-client:latest
            ghcr.io/kenahrens/newboots-client:${{ steps.version.outputs.VERSION }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kenahrens/newboots-server:latest
            ghcr.io/kenahrens/newboots-server:${{ steps.version.outputs.VERSION }}

      - name: Check k8s manifest image
        run: make check-k8s-image 