name: Update K8s Version

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Read version from VERSION file
      id: version
      run: |
        VERSION=$(cat VERSION | tr -d '\n\r')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version from file: $VERSION"
    
    - name: Update K8s manifests
      run: |
        chmod +x scripts/update-k8s-version.sh
        ./scripts/update-k8s-version.sh
    
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changed
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/overlays/default/version-patch.yaml
        git commit -m "Update K8s manifests to version ${{ steps.version.outputs.version }}"
        git push